[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase the timeout for functions that handle image uploads
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]